name: automated tagging

on:
  workflow_dispatch:
    inputs:
      selection:
        description: 'Select Mini App:'
        required: true
        type: choice
        options:
          - p2p
          - cdd

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push tags and create releases
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and Push Tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a "${{ github.event.inputs.selection }}-v${{ github.run_number }}" -m "Release ${{ github.event.inputs.selection }}-v${{ github.run_number }}"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          body: "Description of the changes in this release"
