name: automated tagging

on:
  workflow_dispatch:
    inputs:
      selection:
        description: 'Select Mini App:'
        required: true
        type: choice
        options:
          - p2p
          - cdd

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.run_number }}" -m "Release v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"


